#SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  author: Louis Declerck
  description: Manages DHCP pools and static reservations on FortiGate and MikroTik devices.
  company: Packetflow

  license: GPL-3.0-or-later

  min_ansible_version: "2.16"

  galaxy_tags:
    - dhcp
    - networking
    - fortigate
    - mikrotik
    - homelab

dependencies: []
