# SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  author: Louis Declerck
  description: Manages VLANs on FortiGate, MikroTik, and Ubiquiti UniFi devices.
  company: Packetflow

  license: GPL-3.0-or-later

  min_ansible_version: "2.16"

  galaxy_tags:
    - vlan
    - networking
    - fortigate
    - mikrotik
    - ubiquiti
    - homelab

dependencies: []
